// generated by tools/vo-build.mjs — do not edit
window.TIMELINE = {
  "duration": 41.8,
  "pending": [
    "01-problema",
    "02-derek",
    "03-automatiza",
    "04-agentes",
    "05-apps",
    "06-web",
    "08-fe",
    "09-lema",
    "10-cierre"
  ],
  "lines": [
    {
      "id": "01-problema",
      "speaker": "alan",
      "scene": "dispersas",
      "est": 5.4,
      "text": "Tu empresa tiene ideas para crecer. Pero también tareas que consumen tiempo.",
      "file": null,
      "pending": true,
      "start": 0.8,
      "end": 6.2,
      "dur": 5.4
    },
    {
      "id": "02-derek",
      "speaker": "alan",
      "scene": "orden",
      "est": 4.2,
      "text": "En Derek desarrollamos software para ayudarte a trabajar mejor.",
      "file": null,
      "pending": true,
      "start": 6.75,
      "end": 10.95,
      "dur": 4.2
    },
    {
      "id": "03-automatiza",
      "speaker": "adrian",
      "scene": "automatiza",
      "est": 2.6,
      "text": "Automatizamos procesos repetitivos.",
      "file": null,
      "pending": true,
      "start": 11.5,
      "end": 14.1,
      "dur": 2.6
    },
    {
      "id": "04-agentes",
      "speaker": "adrian",
      "scene": "agentes",
      "est": 4,
      "text": "Y creamos agentes con inteligencia artificial para tareas concretas.",
      "file": null,
      "pending": true,
      "start": 14.65,
      "end": 18.65,
      "dur": 4
    },
    {
      "id": "05-apps",
      "speaker": "alan",
      "scene": "apps",
      "est": 3.6,
      "text": "También aplicaciones y sistemas para organizar tu operación.",
      "file": null,
      "pending": true,
      "start": 19.2,
      "end": 22.8,
      "dur": 3.6
    },
    {
      "id": "06-web",
      "speaker": "alan",
      "scene": "web",
      "est": 3.4,
      "text": "Y páginas web para presentar tu negocio y recibir consultas.",
      "file": null,
      "pending": true,
      "start": 23.35,
      "end": 26.75,
      "dur": 3.4
    },
    {
      "id": "08-fe",
      "speaker": "alan",
      "scene": "fe",
      "est": 4.8,
      "text": "Nuestra fe en Dios nos impulsa a trabajar con integridad y servir con compromiso.",
      "file": null,
      "pending": true,
      "start": 27.3,
      "end": 32.1,
      "dur": 4.8
    },
    {
      "id": "09-lema",
      "speaker": "adrian",
      "scene": "lema",
      "est": 2.6,
      "text": "Derek. Tecnología con propósito.",
      "file": null,
      "pending": true,
      "start": 32.65,
      "end": 35.25,
      "dur": 2.6
    },
    {
      "id": "10-cierre",
      "speaker": "alan",
      "scene": "cierre",
      "est": 2.8,
      "text": "Contanos qué querés mejorar en tu empresa.",
      "file": null,
      "pending": true,
      "start": 35.8,
      "end": 38.6,
      "dur": 2.8
    }
  ]
};
