// Builds the edit timeline from the voice-over.
//   node tools/vo-build.mjs
// For each line in video/script.json it looks for video/audio/vo/<id>.(wav|mp3|m4a).
// If the take exists, its real duration (ffprobe) drives the cut; otherwise the estimate is used
// and the line is marked pending. Outputs:
//   video/timeline.js          window.TIMELINE for the film page
//   video/subs/derek.srt|.vtt  captions from the same timing
//   video/audio/voiceover.wav  assembled, loudness-normalised VO (only when every take exists)
import { readFileSync, writeFileSync, existsSync, mkdirSync } from "node:fs";
import { execFileSync } from "node:child_process";

const S = JSON.parse(readFileSync("video/script.json", "utf8"));
const probe = f => Number(execFileSync("ffprobe", ["-v", "error", "-show_entries", "format=duration", "-of", "csv=p=0", f]).toString().trim());
const findTake = id => ["wav", "mp3", "m4a"].map(e => `video/audio/vo/${id}.${e}`).find(existsSync);

let t = S.lead_in;
const lines = S.lines.map((l, i) => {
  const file = findTake(l.id);
  const dur = file ? probe(file) : l.est;
  const out = { ...l, file: file || null, pending: !file, start: +t.toFixed(3), end: +(t + dur).toFixed(3), dur: +dur.toFixed(3) };
  t += dur + (i < S.lines.length - 1 ? S.gap : 0);
  return out;
});
const duration = +(t + S.tail).toFixed(3);
const pending = lines.filter(l => l.pending).map(l => l.id);
const timeline = { duration, pending, lines };
writeFileSync("video/timeline.js", `// generated by tools/vo-build.mjs — do not edit\nwindow.TIMELINE = ${JSON.stringify(timeline, null, 2)};\n`);

// captions: split long lines at punctuation so no cue is more than ~42 chars per row, 2 rows max
const cues = [];
for (const l of lines) {
  const parts = l.text.match(/[^.,;]+[.,;]?/g).map(s => s.trim()).filter(Boolean);
  const chunks = []; let cur = "";
  for (const p of parts) { if ((cur + " " + p).trim().length > 64 && cur) { chunks.push(cur); cur = p; } else cur = (cur + " " + p).trim(); }
  if (cur) chunks.push(cur);
  const total = chunks.reduce((a, c) => a + c.length, 0);
  let s = l.start;
  for (const c of chunks) { const d = l.dur * c.length / total; cues.push({ a: s, b: s + d, text: c }); s += d; }
}
const ts = (x, sep) => { const ms = Math.round(x * 1000), h = Math.floor(ms / 3600000), m = Math.floor(ms / 60000) % 60, sec = Math.floor(ms / 1000) % 60;
  return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(sec).padStart(2, "0")}${sep}${String(ms % 1000).padStart(3, "0")}`; };
mkdirSync("video/subs", { recursive: true });
writeFileSync("video/subs/derek.srt", cues.map((c, i) => `${i + 1}\n${ts(c.a, ",")} --> ${ts(c.b, ",")}\n${c.text}\n`).join("\n"));
writeFileSync("video/subs/derek.vtt", "WEBVTT\n\n" + cues.map(c => `${ts(c.a, ".")} --> ${ts(c.b, ".")}\n${c.text}\n`).join("\n"));
writeFileSync("video/subs/cues.js", `// generated by tools/vo-build.mjs\nwindow.CUES = ${JSON.stringify(cues.map(c => ({ a: +c.a.toFixed(3), b: +c.b.toFixed(3), text: c.text })))};\n`);

// assemble the VO bed: each take placed at its start time, then normalised to -16 LUFS (social video)
if (!pending.length) {
  const inputs = lines.flatMap(l => ["-i", l.file]);
  const delays = lines.map((l, i) => `[${i}:a]aresample=48000,pan=mono|c0=c0,adelay=${Math.round(l.start * 1000)}[a${i}]`).join(";");
  const mix = `${delays};${lines.map((_, i) => `[a${i}]`).join("")}amix=inputs=${lines.length}:normalize=0,apad=whole_dur=${duration},loudnorm=I=-16:TP=-1.5:LRA=11[out]`;
  execFileSync("ffmpeg", ["-loglevel", "error", "-y", ...inputs, "-filter_complex", mix, "-map", "[out]", "-ar", "48000", "-t", String(duration), "video/audio/voiceover.wav"]);
}
console.log(`duration ${duration}s · ${lines.length - pending.length}/${lines.length} takes${pending.length ? ` · pending: ${pending.join(", ")}` : " · voiceover.wav written"}`);
